[tool.black]
line-length=120
skip-string-normalization=true
exclude='snap_'

[tool.isort]
profile = "black"
lines_between_sections = 1
order_by_type = false
case_sensitive = true
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
no_lines_before = ["LOCALFOLDER"]

# Ruff rules - https://beta.ruff.rs/docs/rules/
# Replased Flake8 with Ruff to improve the performance.
# Here we are using Flake8 rules via Flake8.
[tool.ruff]
select = [
    'E',  # Errors
    'W',  # Warnings
    'F',  # Formatting
    'COM',  # Flake8-commas
    'Q',  # Flake8-quotes
]
ignore = [
    'E402',  # Imports not top of file
    'E741',  # Bad variable names
]

# Same as Black.
line-length = 120

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.ruff.flake8-quotes]
inline-quotes = 'single'

[tool.pylint.FORMAT]
indent-string = '    '
max-line-length = 120

[tool.pylint."MESSAGES CONTROL"]
disable = '''
    I,
    missing-docstring,
    line-too-long,
    no-member,
    fixme,
    broad-except,
    protected-access,
    too-few-public-methods,
    redefined-outer-name,
    too-many-return-statements,
    too-many-statements,
    too-many-arguments,
    too-many-locals,
    too-many-instance-attributes,
    unused-import,
    logging-not-lazy,
    inconsistent-return-statements,
    invalid-name,
    ungrouped-imports,
    wrong-import-order,
    import-error,
    abstract-method,
    no-else-return,
    no-name-in-module,
    duplicate-code,
    len-as-condition,
    too-many-ancestors,
    wrong-import-position,
    missing-timeout
'''

[tool.pylint.REPORTS]
# Replaced {C} with {msg_id} to get the full category code
msg-template = '{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}'

[tool.bandit]
targets ="autocompany/"
exclude_dirs = ['*/tests.py']