# Generated by Django 4.2.5 on 2023-10-03 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('carts', '0003_rename_product_shoppingcartitem_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
